/*
This is an interface
*/

export default Object.freeze({
  'ON_SELECT_FILTER': 'ON_SELECT_FILTER',
  'ON_ROUTE_CHANGE': 'ON_ROUTE_CHANGE',
  'ON_FILTER_SELECTED': 'ON_FILTER_SELECTED',
  'ON_DATA_ERROR': 'ON_DATA_ERROR',
  'ON_DATA_RECEIVED': 'ON_DATA_RECEIVED',
  'REGISTER_LISTENER': 'REGISTER_LISTENER',
  'ON_CALL_SELECTED': 'ON_CALL_SELECTED'
})
